# develop stage
FROM node:18-alpine AS develop-stage
WORKDIR /app
COPY . .
RUN npm install

# build stage
FROM develop-stage AS build-stage
RUN npm run build

# production stage
FROM nginx:1.27.5-alpine AS production-stage
COPY --from=build-stage /app/dist/spa /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]