
services:
  hono:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "8787:8787"
    networks:
      - app-network

  quasar:
    build:
      context: ./frontend
      dockerfile: Dockerfile.client
    networks:
      - app-network
    environment:
      SERVER_HOSTNAME: hono
      SERVER_PORT: 8787
    ports:
      - "9000:80"
    depends_on:
      - hono

networks:
  app-network:
    driver: bridge
