# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY . .
RUN npm install --production

# Expose port
EXPOSE 8787

# Start the server
CMD ["npm", "run", "start"]
